In [1]:
import pandas as pd

df= pd.read_csv("ICRISAT-District Level Data.csv")

df.head()

,Dist Code,Year,State Code,State Name,Dist Name,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),WHEAT AREA (1000 ha),WHEAT PRODUCTION (1000 tons),...,SUGARCANE YIELD (Kg per ha),COTTON AREA (1000 ha),COTTON PRODUCTION (1000 tons),COTTON YIELD (Kg per ha),FRUITS AREA (1000 ha),VEGETABLES AREA (1000 ha),FRUITS AND VEGETABLES AREA (1000 ha),POTATOES AREA (1000 ha),ONION AREA (1000 ha),FODDER AREA (1000 ha)
0,1,1966,14,Chhattisgarh,Durg,548.0,185.0,337.59,44.0,20.0,...,1777.78,0.0,0.0,0.0,5.95,6.64,12.59,0.01,0.60,0.47
1,1,1967,14,Chhattisgarh,Durg,547.0,409.0,747.71,50.0,26.0,...,1500.00,0.0,0.0,0.0,5.77,7.24,13.02,0.01,0.56,1.23
2,1,1968,14,Chhattisgarh,Durg,556.3,468.0,841.27,53.7,30.0,...,1000.00,0.0,0.0,0.0,5.41,7.40,12.81,0.10,0.58,1.02
3,1,1969,14,Chhattisgarh,Durg,563.4,400.8,711.40,49.4,26.5,...,1900.00,0.0,0.0,0.0,5.52,7.16,12.69,0.01,0.56,0.84
4,1,1970,14,Chhattisgarh,Durg,571.6,473.6,828.55,44.2,29.0,...,2000.00,0.0,0.0,0.0,5.45,7.19,12.64,0.02,0.52,0.42

In [2]:
print(df.columns.tolist())

['Dist Code', 'Year', 'State Code', 'State Name', 'Dist Name', 'RICE AREA (1000 ha)', 'RICE PRODUCTION (1000 tons)', 'RICE YIELD (Kg per ha)', 'WHEAT AREA (1000 ha)', 'WHEAT PRODUCTION (1000 tons)', 'WHEAT YIELD (Kg per ha)', 'KHARIF SORGHUM AREA (1000 ha)', 'KHARIF SORGHUM PRODUCTION (1000 tons)', 'KHARIF SORGHUM YIELD (Kg per ha)', 'RABI SORGHUM AREA (1000 ha)', 'RABI SORGHUM PRODUCTION (1000 tons)', 'RABI SORGHUM YIELD (Kg per ha)', 'SORGHUM AREA (1000 ha)', 'SORGHUM PRODUCTION (1000 tons)', 'SORGHUM YIELD (Kg per ha)', 'PEARL MILLET AREA (1000 ha)', 'PEARL MILLET PRODUCTION (1000 tons)', 'PEARL MILLET YIELD (Kg per ha)', 'MAIZE AREA (1000 ha)', 'MAIZE PRODUCTION (1000 tons)', 'MAIZE YIELD (Kg per ha)', 'FINGER MILLET AREA (1000 ha)', 'FINGER MILLET PRODUCTION (1000 tons)', 'FINGER MILLET YIELD (Kg per ha)', 'BARLEY AREA (1000 ha)', 'BARLEY PRODUCTION (1000 tons)', 'BARLEY YIELD (Kg per ha)', 'CHICKPEA AREA (1000 ha)', 'CHICKPEA PRODUCTION (1000 tons)', 'CHICKPEA YIELD (Kg per ha)', 'PIGEONPEA AREA (1000 ha)', 'PIGEONPEA PRODUCTION (1000 tons)', 'PIGEONPEA YIELD (Kg per ha)', 'MINOR PULSES AREA (1000 ha)', 'MINOR PULSES PRODUCTION (1000 tons)', 'MINOR PULSES YIELD (Kg per ha)', 'GROUNDNUT AREA (1000 ha)', 'GROUNDNUT PRODUCTION (1000 tons)', 'GROUNDNUT YIELD (Kg per ha)', 'SESAMUM AREA (1000 ha)', 'SESAMUM PRODUCTION (1000 tons)', 'SESAMUM YIELD (Kg per ha)', 'RAPESEED AND MUSTARD AREA (1000 ha)', 'RAPESEED AND MUSTARD PRODUCTION (1000 tons)', 'RAPESEED AND MUSTARD YIELD (Kg per ha)', 'SAFFLOWER AREA (1000 ha)', 'SAFFLOWER PRODUCTION (1000 tons)', 'SAFFLOWER YIELD (Kg per ha)', 'CASTOR AREA (1000 ha)', 'CASTOR PRODUCTION (1000 tons)', 'CASTOR YIELD (Kg per ha)', 'LINSEED AREA (1000 ha)', 'LINSEED PRODUCTION (1000 tons)', 'LINSEED YIELD (Kg per ha)', 'SUNFLOWER AREA (1000 ha)', 'SUNFLOWER PRODUCTION (1000 tons)', 'SUNFLOWER YIELD (Kg per ha)', 'SOYABEAN AREA (1000 ha)', 'SOYABEAN PRODUCTION (1000 tons)', 'SOYABEAN YIELD (Kg per ha)', 'OILSEEDS AREA (1000 ha)', 'OILSEEDS PRODUCTION (1000 tons)', 'OILSEEDS YIELD (Kg per ha)', 'SUGARCANE AREA (1000 ha)', 'SUGARCANE PRODUCTION (1000 tons)', 'SUGARCANE YIELD (Kg per ha)', 'COTTON AREA (1000 ha)', 'COTTON PRODUCTION (1000 tons)', 'COTTON YIELD (Kg per ha)', 'FRUITS AREA (1000 ha)', 'VEGETABLES AREA (1000 ha)', 'FRUITS AND VEGETABLES AREA (1000 ha)', 'POTATOES AREA (1000 ha)', 'ONION AREA (1000 ha)', 'FODDER AREA (1000 ha)']

In [3]:
df = df.rename(columns={
    "State Name": "state",
    "Dist Name": "district",
    "Year": "year",
    
    "RICE AREA (1000 ha)": "rice_area",
    "RICE PRODUCTION (1000 tons)": "rice_production",
    
    "WHEAT AREA (1000 ha)": "wheat_area",
    "WHEAT PRODUCTION (1000 tons)": "wheat_production"
})

In [4]:
df = df[[
    "state",
    "district",
    "year",
    "rice_area",
    "rice_production",
    "wheat_area",
    "wheat_production"
]]

In [5]:
df.head()

,state,district,year,rice_area,rice_production,wheat_area,wheat_production
0,Chhattisgarh,Durg,1966,548.0,185.0,44.0,20.0
1,Chhattisgarh,Durg,1967,547.0,409.0,50.0,26.0
2,Chhattisgarh,Durg,1968,556.3,468.0,53.7,30.0
3,Chhattisgarh,Durg,1969,563.4,400.8,49.4,26.5
4,Chhattisgarh,Durg,1970,571.6,473.6,44.2,29.0

In [6]:
import xml.etree.ElementTree as ET

root = ET.Element("datasets")

for _, row in df.iterrows():
    record = ET.SubElement(root, "record")

    ET.SubElement(record, "state").text = str(row["state"])
    ET.SubElement(record, "district").text = str(row["district"])
    ET.SubElement(record, "year").text = str(row["year"])

    crops = ET.SubElement(record, "crops")

    # Rice
    rice = ET.SubElement(crops, "crop", name="rice")
    ET.SubElement(rice, "area").text = str(row["rice_area"])
    ET.SubElement(rice, "production").text = str(row["rice_production"])

    # Wheat
    wheat = ET.SubElement(crops, "crop", name="wheat")
    ET.SubElement(wheat, "area").text = str(row["wheat_area"])
    ET.SubElement(wheat, "production").text = str(row["wheat_production"])

tree = ET.ElementTree(root)
tree.write("data.xml")

print("XML file created successfully!")

XML file created successfully!

In [10]:
with open("data.xml", "r") as f:
    for i in range(10):
        line = f.readline()
        print(line[:200])   # only first 200 characters

<datasets><record><state>Chhattisgarh</state><district>Durg</district><year>1966</year><crops><crop name="rice"><area>548.0</area><production>185.0</production></crop><crop name="wheat"><area>44.0</ar

In [7]:
import xml.etree.ElementTree as ET

tree = ET.parse("data.xml")
root = tree.getroot()

for result in root.findall(".//record[state='Maharashtra']/crops/crop[@name='rice']/production"):
    print(result.text)

3.0
3.0
2.0
2.0
2.1
2.3
0.8
2.1
1.8
1.6
1.7
2.2
2.0
1.3
1.6
0.8
1.5
1.0
0.7
0.0
0.0
0.0
0.5
0.0
0.6
0.5
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
172.0
252.0
187.0
201.4
248.1
221.6
100.1
266.3
238.1
285.8
233.7
326.0
265.2
222.8
292.4
310.7
268.9
312.8
270.7
255.7
170.0
283.0
299.8
283.5
288.0
268.6
285.0
303.4
290.7
310.8
393.0
357.5
272.8
302.0
175.3
345.1
159.8
397.5
335.4
310.6
257.4
309.25
303.4
290.76
280.58
343.98
362.94
334.0
328.7
306.5
375.3
246.3
160.0
242.0
187.0
179.8
245.8
195.0
163.0
203.7
214.2
235.8
215.2
290.8
268.1
238.3
274.1
284.8
283.1
272.4
323.3
262.2
259.0
308.0
345.6
299.2
251.4
335.6
294.5
328.4
321.1
330.0
332.2
351.8
347.7
328.5
291.7
356.8
277.8
376.3
297.2
295.0
314.5
334.62
359.8
329.43
299.08
306.16
333.33
365.9
350.8
339.9
309.1
310.8
108.0
166.0
161.0
146.3
199.4
172.7
142.1
208.1
197.6
232.1
203.4
222.2
252.8
211.6
256.0
278.4
252.6
277.7
316.0
293.0
228.0
306.0
309.6
360.9
339.5
342.3
333.2
355.0
371.1
389.8
404.4
377.1
438.5
374.1
364.6
407.6
321.4
484.5
406.5
419.4
440.4
410.49
417.1
407.55
430.11
437.44
428.18
451.6
448.3
370.2
445.3
430.7
22.0
38.0
34.0
23.9
36.2
29.9
5.3
36.6
36.3
59.5
58.7
63.9
53.5
54.3
45.2
57.8
41.2
54.7
45.4
29.9
21.0
31.0
46.9
39.1
41.8
31.9
49.1
57.9
55.3
37.0
60.5
59.1
57.2
57.2
39.8
56.3
43.9
66.3
70.2
58.7
49.6
68.4
65.8
18.84
24.03
77.8
80.79
93.3
86.7
101.1
145.8
153.6
10.0
12.0
6.0
7.3
10.2
9.2
5.3
11.1
9.1
14.2
16.3
26.1
23.8
16.8
18.2
21.9
14.9
19.5
23.9
9.5
9.0
13.0
24.6
25.5
25.2
14.8
18.3
29.3
25.6
16.8
27.0
27.1
23.8
14.2
6.7
17.9
18.7
24.6
15.1
35.9
19.0
34.74
24.9
15.24
31.38
37.0
35.76
30.0
9.0
20.0
39.9
44.2
1.0
4.0
2.0
2.8
5.3
3.6
3.1
6.8
13.2
12.3
23.1
22.3
15.3
14.0
17.0
14.2
12.5
13.9
13.9
3.8
4.0
5.0
5.2
6.2
3.9
5.7
2.0
1.3
1.1
1.5
2.0
1.6
1.9
1.7
2.1
0.7
0.8
1.1
0.4
0.3
0.1
0.14
0.0
0.09
0.0
0.3
0.0
0.0
0.0
0.0
0.0
0.0
5.0
8.0
7.0
5.0
5.6
5.8
1.0
6.7
10.0
15.4
21.0
17.9
13.8
8.7
15.4
10.0
10.3
11.8
9.0
6.4
7.0
8.0
8.1
9.8
7.1
4.6
10.4
6.4
6.0
9.3
7.6
12.6
7.4
8.0
3.8
4.1
1.7
5.9
5.8
3.5
6.6
10.24
9.1
2.8
7.03
7.8
4.61
19.0
2.2
17.2
26.2
37.3
35.0
45.0
45.0
34.3
36.5
37.1
11.8
51.9
77.1
93.1
103.6
110.4
82.0
82.0
109.7
82.8
71.5
87.5
78.2
69.0
65.0
72.0
89.8
85.6
85.9
63.5
81.8
53.8
72.7
78.8
81.7
71.7
73.7
89.2
75.2
86.4
40.0
84.7
85.1
73.8
68.9
78.2
75.5
51.18
71.92
85.6
106.16
153.2
136.1
107.3
115.4
124.0
28.0
23.0
22.0
28.6
30.1
31.6
7.5
30.5
33.6
41.8
51.1
45.7
55.6
54.9
62.9
56.9
54.4
63.9
72.5
67.8
47.0
66.0
85.7
90.6
68.7
75.2
68.3
79.6
62.1
56.7
91.3
58.0
100.2
71.1
51.3
77.2
71.2
73.4
72.9
73.4
93.3
102.4
109.3
76.9
82.24
83.0
70.04
75.6
94.7
79.7
82.1
83.0
13.0
13.0
12.0
15.0
15.7
15.9
3.5
16.1
20.7
29.6
41.5
31.1
31.6
27.3
36.2
27.3
27.7
32.7
32.1
34.8
23.0
30.0
36.0
36.5
27.5
29.4
37.3
31.3
18.5
35.0
33.9
31.9
51.5
47.2
40.4
47.2
28.4
39.5
44.2
39.5
28.9
43.61
38.7
35.07
53.87
33.7
33.74
25.5
31.4
43.4
42.9
39.3
3.0
3.0
6.0
4.9
5.1
3.3
0.3
7.5
5.2
14.5
14.7
16.0
10.5
5.1
11.1
7.4
6.1
7.2
5.9
1.1
3.0
2.0
6.4
5.6
3.5
3.4
4.8
2.7
2.1
2.1
3.1
2.4
3.3
4.2
3.4
0.8
0.3
0.1
0.1
0.1
0.1
0.33
0.1
0.01
0.23
0.2
0.09
0.1
0.1
0.0
0.04
0.07
129.0
91.0
88.0
90.0
116.5
111.6
67.1
131.7
128.8
172.2
198.1
210.6
202.6
168.2
213.3
238.7
182.6
215.2
231.5
242.3
175.0
187.0
251.8
234.7
259.3
253.0
267.6
244.1
237.7
228.5
279.7
252.9
289.8
262.6
233.7
290.5
234.7
248.3
281.3
247.8
286.4
338.02
287.2
293.27
323.12
280.88
283.96
341.8
338.6
276.6
397.8
334.3
1.0
2.0
3.0
2.8
2.7
1.1
0.2
3.1
2.5
5.7
6.7
10.5
10.3
5.7
9.3
9.3
4.9
7.0
4.5
3.2
2.0
2.0
3.3
4.3
3.2
1.5
2.5
2.8
3.2
1.3
2.7
4.5
1.0
1.1
1.1
0.7
0.3
0.5
0.4
0.1
0.1
0.0
0.0
0.0
0.02
0.0
0.0
0.0
0.0
0.0
3.1
0.0
3.0
6.0
8.0
6.9
6.6
2.6
2.8
7.9
7.6
35.3
24.6
40.6
33.8
26.0
29.1
32.7
15.3
22.2
12.5
16.2
14.0
15.0
22.8
23.8
25.9
10.0
17.8
19.0
21.6
15.6
15.9
7.0
10.3
13.2
12.2
15.0
14.0
8.4
4.9
4.2
5.2
4.74
2.2
1.51
2.47
0.8
0.33
0.3
0.0
0.0
0.0
0.0
3.0
3.0
4.0
4.3
3.5
0.7
0.1
2.8
2.3
6.2
9.6
11.9
12.0
7.2
10.6
4.3
4.9
6.0
4.2
3.5
2.0
3.0
4.2
6.0
6.4
2.1
4.3
4.2
4.2
2.0
3.5
8.0
1.4
1.73
2.0
1.5
0.6
1.0
0.6
0.9
1.5
0.7
0.4
0.17
0.34
0.28
0.27
0.3
0.1
0.0
0.07
0.03
10.0
12.0
14.0
15.1
13.9
7.8
0.7
10.7
12.7
29.3
38.4
56.9
39.4
39.0
44.0
54.4
25.4
39.8
25.9
26.5
13.0
10.0
20.8
32.8
29.3
10.0
23.2
31.3
27.1
18.1
21.4
20.3
15.8
15.6
20.1
24.4
15.3
13.4
8.2
6.7
9.4
10.45
4.2
1.49
2.71
1.5
2.09
0.4
0.1
0.1
1.3
1.2
10.0
12.0
13.0
13.1
15.5
9.0
0.3
22.6
15.0
40.3
26.2
34.0
40.2
35.0
34.4
51.7
24.7
34.3
22.9
15.7
2.4
13.0
19.0
33.1
42.7
9.3
26.5
27.7
21.9
17.6
28.3
10.2
13.4
20.2
21.4
15.8
14.4
9.3
12.9
14.7
13.3
12.8
3.2
4.97
6.19
7.3
7.77
11.5
3.6
0.9
2.1
3.0
1.0
1.0
2.0
3.1
3.4
2.3
1.2
2.5
1.3
2.8
2.4
3.9
4.1
3.6
4.4
5.6
2.1
2.6
1.4
1.0
1.0
1.0
3.8
1.9
2.6
1.8
2.6
2.8
1.1
0.6
0.8
0.3
0.4
0.1
0.2
0.2
0.1
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
3.0
4.0
3.3
4.1
3.6
1.5
3.6
3.7
5.7
7.1
8.3
10.7
7.6
8.9
11.4
5.1
6.1
3.2
4.8
4.0
4.0
2.9
3.8
5.0
3.2
4.4
6.1
6.1
2.7
2.0
1.8
2.1
1.2
0.8
1.3
0.7
0.3
0.2
0.1
0.1
0.08
0.1
0.16
0.0
0.2
0.0
0.0
0.0
0.0
0.0
0.0
2.0
5.0
6.0
5.0
4.6
4.5
1.8
5.7
6.2
6.9
8.7
11.1
12.2
8.5
10.5
15.3
6.8
9.2
5.4
8.4
7.0
8.0
5.6
7.5
5.7
6.1
7.5
9.6
7.9
6.1
8.3
5.5
6.1
5.6
4.4
9.7
7.2
6.0
4.2
5.0
4.6
5.18
1.8
6.23
2.76
3.1
1.55
0.8
1.6
1.2
4.6
3.0
4.0
5.0
6.0
5.4
6.3
6.4
2.4
6.2
7.8
11.3
8.5
13.7
15.4
12.2
12.7
16.6
8.3
8.9
3.8
5.2
5.0
4.0
4.8
5.2
7.0
3.5
4.8
4.6
5.0
2.8
4.6
3.5
4.0
4.6
4.3
4.8
2.4
2.0
0.8
0.9
0.3
0.4
0.2
0.33
0.0
0.1
0.04
0.0
0.0
0.0
0.0
0.0
1.0
2.0
5.0
6.8
7.5
8.0
3.8
7.0
5.6
10.3
7.5
10.9
14.1
9.4
6.7
13.9
11.2
7.5
4.8
10.0
6.0
2.0
7.8
3.9
2.5
1.7
2.7
2.2
1.5
1.6
1.3
0.4
0.5
0.3
0.3
0.3
0.3
0.2
0.2
0.2
0.1
0.09
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
11.0
25.0
24.0
25.6
35.0
22.4
10.8
34.4
31.6
54.9
44.6
57.1
58.8
48.9
61.5
63.1
40.6
51.2
29.0
65.4
58.0
32.0
73.6
42.6
38.4
40.1
45.9
51.7
50.1
51.3
47.1
43.6
40.3
42.2
37.4
55.1
42.1
65.3
41.6
62.9
70.6
75.6
54.6
81.27
70.3
117.4
100.45
105.2
95.5
107.3
170.4
183.6
158.0
247.0
259.0
290.9
346.2
276.6
128.7
266.1
215.6
448.8
325.5
403.2
365.4
260.0
426.7
403.5
254.2
468.8
197.0
412.7
361.0
97.0
532.6
376.0
425.6
354.4
384.6
440.4
385.3
482.9
383.3
359.5
386.9
476.4
306.6
442.0
371.3
538.8
224.5
577.5
494.3
672.69
265.4
381.82
607.65
633.82
734.97
649.59
699.5
573.8
888.7
449.1
165.0
191.0
212.0
243.7
256.3
210.8
100.1
285.3
166.5
418.0
291.2
306.3
318.9
260.1
339.7
361.9
318.0
426.0
198.5
333.7
264.0
212.0
440.9
300.8
346.9
239.5
384.7
388.8
398.1
463.9
378.8
348.1
325.6
416.6
230.9
389.8
186.7
386.7
234.5
437.8
405.0
483.14
264.5
186.42
400.48
390.29
490.78
450.2
319.6
247.9
530.8
287.3

In [12]:
pip install streamlit

Requirement already satisfied: streamlit in c:\users\adrian vinod\anaconda3\lib\site-packages (1.51.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in c:\users\adrian vinod\anaconda3\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\adrian vinod\anaconda3\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in c:\users\adrian vinod\anaconda3\lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\users\adrian vinod\anaconda3\lib\site-packages (from streamlit) (8.2.1)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\adrian vinod\anaconda3\lib\site-packages (from streamlit) (2.3.5)
Requirement already satisfied: packaging<26,>=20 in c:\users\adrian vinod\anaconda3\lib\site-packages (from streamlit) (25.0)
Requirement already satisfied: pandas<3,>=1.4.0 in c:\users\adrian vinod\anaconda3\lib\site-packages (from streamlit) (2.3.3)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\adrian vinod\anaconda3\lib\site-packages (from streamlit) (12.0.0)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\adrian vinod\anaconda3\lib\site-packages (from streamlit) (5.29.3)
Requirement already satisfied: pyarrow<22,>=7.0 in c:\users\adrian vinod\anaconda3\lib\site-packages (from streamlit) (21.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\adrian vinod\anaconda3\lib\site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\adrian vinod\anaconda3\lib\site-packages (from streamlit) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\adrian vinod\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\users\adrian vinod\anaconda3\lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\adrian vinod\anaconda3\lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\adrian vinod\anaconda3\lib\site-packages (from streamlit) (3.1.45)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\users\adrian vinod\anaconda3\lib\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: jinja2 in c:\users\adrian vinod\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\adrian vinod\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\adrian vinod\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.7.0)
Requirement already satisfied: colorama in c:\users\adrian vinod\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\adrian vinod\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\adrian vinod\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\adrian vinod\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\adrian vinod\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\adrian vinod\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\adrian vinod\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\adrian vinod\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\adrian vinod\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\adrian vinod\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.11.12)
Requirement already satisfied: attrs>=22.2.0 in c:\users\adrian vinod\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\adrian vinod\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\adrian vinod\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\adrian vinod\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.28.0)
Requirement already satisfied: six>=1.5 in c:\users\adrian vinod\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\adrian vinod\anaconda3\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.2)
Note: you may need to restart the kernel to use updated packages.